### ISSUE TITLE
Register command line tool reader.py

### ISSUE THREAD

**Issue by sfeister** [flash-center/PRadReader#1]
The command line tool found in "reader.py" is not currently registered upon installation. It should be registered so the user can call it from bash, etc!

Whoever implements gets to choose a name :-)

**Ideas:**
prread
pradread
radread
pr-read
...

**Do NOT use (too generic):**
reader
read

**Comment by sfeister** [comment]
Command line tool is now called pr-read.py and is in [PRadReader]/bin; still needs to be registered and can be renamed by whoever does so

**Comment by jtlaune** [comment]
I have included a script in pradreader/scripts/pradreader.py that reads in & accepts an input filename & an output filename (optional). I have added it to the setup.py so that it registers as a CLT upon installation.
